name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: 192.168.55.197:5000
  BACKEND_IMAGE: hello-world-backend
  FRONTEND_IMAGE: hello-world-frontend
  NAMESPACE: hello-world-app
  KUBERNETES_CONTEXT: kubernetes-admin@kubernetes  # 실제 kubeconfig context로 변경하세요

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Docker and Registry
        run: |
          # Docker 설정 확인
          echo "Docker daemon configuration:"
          cat /etc/docker/daemon.json || echo "No daemon.json found"
          
          # Docker 버전 확인
          docker version
          
          # 레지스트리 연결 테스트
          curl -v http://${{ env.REGISTRY }}/v2/ || echo "Registry connection failed"

      - name: Build and push Backend Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest ./backend
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Build and push Frontend Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest ./frontend
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Update Kubernetes manifests
        run: |
          # 이미지 태그 업데이트
          sed -i "s|image: hello-world-backend:latest|image: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}|g" k8s/backend-deployment.yaml
          sed -i "s|image: hello-world-frontend:latest|image: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}|g" k8s/frontend-deployment.yaml

      - name: Create namespace if not exists
        run: |
          kubectl get namespace ${{ env.NAMESPACE }} || kubectl create namespace ${{ env.NAMESPACE }}

      - name: Deploy to Kubernetes
        run: |
          # ConfigMap 및 Secret 적용
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/nginx-configmap.yaml
          
          # MySQL 배포
          kubectl apply -f k8s/mysql-deployment.yaml
          
          # MySQL이 준비될 때까지 대기 (최대 2분)
          echo "Waiting for MySQL to be ready..."
          kubectl wait --for=condition=ready pod -l app=mysql -n ${{ env.NAMESPACE }} --timeout=120s || echo "MySQL pods not ready, continuing anyway"
          
          # 백엔드 배포
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          
          # 프론트엔드 배포
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          
          # Nginx 배포
          kubectl apply -f k8s/nginx-deployment.yaml
          kubectl apply -f k8s/nginx-service.yaml
          
          # Ingress 배포 (선택 사항)
          if [ -f k8s/ingress.yaml ]; then
            kubectl apply -f k8s/ingress.yaml
          fi

      - name: Verify deployment
        run: |
          echo "Checking deployment status..."
          kubectl get pods -n ${{ env.NAMESPACE }}
          kubectl get svc -n ${{ env.NAMESPACE }}
          
          # Nginx 서비스의 외부 IP 또는 NodePort 확인
          echo "Access your application at:"
          kubectl get svc nginx -n ${{ env.NAMESPACE }}

      - name: Cleanup old images (optional)
        if: success()
        run: |
          echo "Cleaning up old images from registry..."
          # 이 부분은 로컬 레지스트리 API를 사용하여 오래된 이미지를 정리하는 스크립트를 추가할 수 있습니다
          # 예: curl -X DELETE http://localhost:5000/v2/${{ env.BACKEND_IMAGE }}/manifests/[old-tag] 